---
title: 5 RCircos histogram plot with CNV data
abstract: ~
author: |
  Authors: Hongen Zhang\  
  Reviser: Tianze Cao
date: '2025-06-05'
vignette: |-
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{RCircos_Demo_Human}
  %\VignetteDepends{RCircos}
output:
  bookdown::html_document2:
    base_format: rmarkdown::html_vignette
    number_sections: no
    math_method: katex
link-citations: yes
---
```{r include=FALSE}
library(knitr)
opts_chunk$set(
concordance=TRUE
)
```
This demo draw chromosome ideogram with padding between chromosomes, highlights, chromosome names, and histogram.

```{r}

#  Load RCircos package and defined parameters
library(RCircos);


#  Load human cytoband data and gene expression data

data(RCircos.Histogram.Data);
data(UCSC.HG19.Human.CytoBandIdeogram);
cyto.info <- UCSC.HG19.Human.CytoBandIdeogram;

#  Setup RCircos core components:
RCircos.Set.Core.Components(cyto.info, NULL, 10, 0);


#  Open the graphic device (here a pdf file)
RCircos.Set.Plot.Area();


#  Draw chromosome ideogram
message("Draw chromosome ideogram ...\n");

RCircos.Chromosome.Ideogram.Plot();
title("RCircos Histogram Plot Demo");

#  Plot histogram Inside of chromosome ideogram
hist.data <- RCircos.Histogram.Data;
hist.colors <- rep("blue", nrow(hist.data))
rows <- which(hist.data$Data>0.4)
hist.colors[rows] <- "red";
hist.data["PlotColor"] <- hist.colors;

data.col <- 4; 
track.num <- 1;
RCircos.Histogram.Plot(hist.data, data.col, track.num, "in");

#  Close the graphic device and clear memory
message("RCircos Histogram Demo Done!");
```
