---
title: 10 RCircos Ribbon plot
abstract: ~
author: |
  Authors: Hongen Zhang\  
  Reviser: Tianze Cao
date: '2025-06-05'
vignette: |-
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{RCircos_Demo_Human}
  %\VignetteDepends{RCircos}
output:
  bookdown::html_document2:
    base_format: rmarkdown::html_vignette
    number_sections: no
    math_method: katex
link-citations: yes
---
```{r include=FALSE}
library(knitr)
opts_chunk$set(
concordance=TRUE
)
```
This demo draw ribbon links between chromosomes

```{r}
# Load RCircos library

library(RCircos);

# Load human cytoband data and link data

data(RCircos.Ribbon.Data); data(UCSC.HG19.Human.CytoBandIdeogram); 
cyto.info <- UCSC.HG19.Human.CytoBandIdeogram;

# Setup RCircos core components:

RCircos.Set.Core.Components(cyto.info, NULL, 10, 0);

RCircos.Set.Plot.Area();

# Draw chromosome ideogram

RCircos.Chromosome.Ideogram.Plot(); 
title("RCircos Ribbon Plot Demo");

# Link lines. Link data has only paired chromosome

# locations in each row and link lines are always

# drawn inside of chromosome ideogram.

ribbon.data <- RCircos.Ribbon.Data; 
ribbon.data["PlotColor"] <- c("red", "blue", "green", "cyan");

track.num <- 11; 
RCircos.Ribbon.Plot(ribbon.data, track.num, FALSE);

message("RCircos Ribbon Plot Demo Done!"); 
```
