---
title: 11 RCircos scatter plot with CNV data
abstract: ~
author: |
  Authors: Hongen Zhang\  
  Reviser: Tianze Cao
date: '2025-06-05'
vignette: |-
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{RCircos_Demo_Human}
  %\VignetteDepends{RCircos}
output:
  bookdown::html_document2:
    base_format: rmarkdown::html_vignette
    number_sections: no
    math_method: katex
link-citations: yes
---
```{r include=FALSE}
library(knitr)
opts_chunk$set(
concordance=TRUE
)
```
This demo draw chromosome ideogram with padding between chromosomes, highlights, chromosome names, and scatters.

```{r}
#   Load RCircos library

library(RCircos);

#   Load human cytoband data and scatterplot data

data(RCircos.Scatter.Data);
	if(length(grep("chr", RCircos.Scatter.Data$chromosome)) == 0)
		RCircos.Scatter.Data$chromosome <- paste0("chr", 
    RCircos.Scatter.Data$chromosome);

data(UCSC.HG19.Human.CytoBandIdeogram);
cyto.info <- UCSC.HG19.Human.CytoBandIdeogram;


#   Setup RCircos core components:

RCircos.Set.Core.Components(cyto.info, NULL, 10, 0);

RCircos.Set.Plot.Area();

#   Draw chromosome ideogram

RCircos.Chromosome.Ideogram.Plot();
title("RCircos Scatter Plot Demo");

#   Scatterplot 

scatter.data <- RCircos.Scatter.Data;
scatter.colors <- rep("cyan", nrow(scatter.data));
scatter.colors[which(scatter.data$seg.mean>=2)] <- "red";
scatter.colors[which(scatter.data$seg.mean<=-2)] <- "blue";
scatter.data["PlotColor"] <- scatter.colors;

data.col <- 5;
track.num <- 6; 
RCircos.Scatter.Plot(scatter.data, data.col, track.num, "in", 1);

message("RCircos Scatter Plot Demo Done!");

```
