---
title: 13 RCircos tile plot
abstract: ~
author: |
  Authors: Hongen Zhang\  
  Reviser: Tianze Cao
date: '2025-06-05'
vignette: |-
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{RCircos_Demo_Human}
  %\VignetteDepends{RCircos}
output:
  bookdown::html_document2:
    base_format: rmarkdown::html_vignette
    number_sections: no
    math_method: katex
link-citations: yes
---
```{r include=FALSE}
library(knitr)
opts_chunk$set(
concordance=TRUE
)
```
This demo draw chromosome ideogram with padding between chromosomes, highlights, chromosome names, and tile plot.

```{r}
#  Load RCircos library

library(RCircos);

#  Load human cytoband data and gene expression data

data(RCircos.Tile.Data);
data(UCSC.HG19.Human.CytoBandIdeogram);
cyto.info <- UCSC.HG19.Human.CytoBandIdeogram;

#  Setup RCircos core components:

RCircos.Set.Core.Components(cyto.info, NULL, 10, 0);

RCircos.Set.Plot.Area();

#  Draw chromosome ideogram

RCircos.Chromosome.Ideogram.Plot();
title("RCircos Tile Plot Demo");

#  Tile plot. Note: tile plot data have chromosome 
#  locations only and each data file is for one track

tile.data <- RCircos.Tile.Data;
tile.colors <- rainbow(nrow(tile.data));
tile.data["PlotColor"] <- tile.colors;

track.num <- 9;
RCircos.Tile.Plot(tile.data, track.num, "in");

message("RCircos Tile Plot Demo Done!");

```
